### ISSUE TITLE
TODO dla tablicy

### ISSUE THREAD

**Issue by matiutd888** [matiutd888/IO-2021#1]
- [x] Pole tekstowe
- [x]  gumka
 - [x]  ctrl z
 - [x]  zmniejszenie mocy przyblizania (Byc moze jakis suwak ktory ustala predkosc scrolla?)
 - [ ]  zmiana kolorków kształtów
 - [x]  Obiekty powinny pojawiać się w centrum canvasa
 - [ ]  Obiekty powinny mieć kolorowe te elementy do zmieniania ich kształtu bo się zlewa z tłem
 - [ ]  Background wywalić
 - [x]  Canvas powinien ładniej mieścić się na ekranie
 - [x] Przybliżanie powinno być "kierunkowe"
 - [ ] Pole tekstowe nie powinno być w "shapes"
 - [ ] Clear i restore marnują całą liniję, canvas bez nich mógłby być wyższy (nwm jak to zmienić ale może jakoś się da xd)
 - [ ] Przycisk co cofa na przybliżenie 100% (mocno inspirowane miro :) )
 - [ ] Autozapis
 - [ ] Zmiejszenie przycisku z dodaniem png, kliknięcie obok już go triggeruje
